### ISSUE TITLE
[bug] 在屏幕边缘会 按快捷键，会出现部分不可见。

### ISSUE THREAD

**Issue by icbyhero** [CleanClip/CleanClipApp#2]
问题简述：
屏幕边缘会 调出主界面，会出现部分不可见。
问题频率：
必现
复现步骤：
光标移动到屏幕边缘框
详细描述：
主界面面
截图视频等：
<img width="54" alt="image" src="https://github.com/auv1107/cleancliprun/assets/34714930/3c731ae4-2f87-46a8-9ec0-9c8f60958d36">
ps: 我没有看到bug标签，不好意思。

**Comment by auv1107** [comment]
成功复现，准备修复了

**Comment by icbyhero** [comment]
总算复现了.

**Comment by s1ntoneli** [comment]
该beta版本中已修复，马上发布正式版：https://github.com/CleanClip/CleanClipApp/releases/tag/2.2.0-beta.1
