### ISSUE TITLE
[bug] 偏好设置中保留历史记录条数最大是10

### ISSUE THREAD

**Issue by uuip** [CleanClip/CleanClipApp#20]
版本 2.2.5

问题简述：保留历史记录条数最大是10
问题频率：必现
复现步骤：设置为超过10，会自动改为10. 用其他app时曾设置为1000.

**Comment by s1ntoneli** [comment]
已复现

**Comment by s1ntoneli** [comment]
已上线，丰富了相关功能
![CleanShot 2024-11-18 at 18 55 16@2x](https://github.com/user-attachments/assets/74f541d4-f285-4347-8019-0d26e9ed5f53)
