### ISSUE TITLE
“Format Brush” popup menu is blank.

### ISSUE THREAD

**Issue by SK9MM777** [CleanClip/CleanClipApp#22]
CleanClip Pro version 2.2.7 (20207)

An issue with the text display in the “Format Brush” popup menu. When the menu is opened, it shows a blank, white box with only a button labeled “on” visible, but the rest of the text options are missing or not displayed.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/1fe4bb9e-9e7d-4cf6-9f46-b44c17cb661c">

**Comment by s1ntoneli** [comment]
Got it, will adapt to dark mode right away.

**Comment by s1ntoneli** [comment]
Fixed!

![CleanShot 2024-11-19 at 09 58 40@2x](https://github.com/user-attachments/assets/b0363693-eed6-45f3-96df-14006cb6cc89)
