### ISSUE TITLE
请问可否考虑增加一个在特定时间后删除记录的剪贴板的功能？cleanclip现在太大了[苦涩]

### ISSUE THREAD

**Issue by yzy-lex** [CleanClip/CleanClipApp#24]
![CleanShot 2024-10-17 at 16 55 26@2x](https://github.com/user-attachments/assets/1cfc8438-65fd-4d80-accd-27430c10eb36)

**Comment by s1ntoneli** [comment]
已经增加，即将上线

**Comment by yzy-lex** [comment]
谢谢大佬❤️在 2024年11月12日，17:35，Sintone ***@***.***> 写道：﻿
已经增加，即将上线

**Comment by s1ntoneli** [comment]
2.3.0 已上线
