### ISSUE TITLE
预览大图片时要等待1-2s。是否可以改进预览方式加快预览速度？

### ISSUE THREAD

**Issue by chenxiccc** [CleanClip/CleanClipApp#25]
一些剪贴板图片，如果是全屏截图。预览时要转圈1-2s才能显示出预览图。是否可以改进预览功能加快预览速度？
之前用Maccy，可以即时出现。

**Comment by s1ntoneli** [comment]
设置成0就可以了
![CleanShot 2024-11-12 at 17 32 43@2x](https://github.com/user-attachments/assets/97ca4130-a7a9-4263-8184-57dd774bbafa)
