### ISSUE TITLE
[feature]高亮当前的粘贴项

### ISSUE THREAD

**Issue by neo729** [CleanClip/CleanClipApp#4]
1. 高亮当前的粘贴项目
2. 当前的↩️不是很醒目，如果能高亮所选项，可以更方便区分。

**Comment by auv1107** [comment]
设计问题，暗黑模式稍微优化了下，暂时不做大改动，优先级较低。

**Comment by s1ntoneli** [comment]
已在该版本解决，马上发布正式版：https://github.com/CleanClip/CleanClipApp/releases/tag/2.2.0-beta.1

**Comment by gh0stkey** [comment]
我不知道此处的高亮所指是什么，是否能在搜索的时候增加一个匹配到相关关键词的高亮呢？

<img width="374" alt="Image" src="https://github.com/user-attachments/assets/7432a2d3-5eca-44b3-a225-02d6809f0803" />
