### ISSUE TITLE
【Bug】WPS 下无法唤醒快捷窗口，附件是演示视频。

### ISSUE THREAD

**Issue by uclort** [CleanClip/CleanClipApp#7]
另外反馈邮箱无法接收邮件了，提示对方邮箱已满

[CleanShot 2024-03-05 at 10.57.31.mp4.zip](https://github.com/auv1107/cleancliprun/files/14490036/CleanShot.2024-03-05.at.10.57.31.mp4.zip)

**Comment by auv1107** [comment]
WPS 使用的开发框架非常规，难以定位。所以快捷窗口显示到了窗口外。

无法定位到光标处，将改成定位到窗口中心。

**Comment by uclort** [comment]
> WPS 使用的开发框架非常规，难以定位。所以快捷窗口显示到了窗口外。
> 
> 无法定位到光标处，将改成定位到窗口中心。

还有两个问题，不知道是不是一个原因。
 1. 我外接显示器使用，Mac 自身盒盖，打开微信窗口，正常聊天，快捷键唤出快捷面板，正常，然后 cmd+w 关闭微信窗口，这个时候桌面是没有任何窗口的，使用快捷键唤出快捷面板，位置是顶部少一半的，附件我提供视频。
 2. 默认设置 5 条历史纪录，然后按下 tab 键，如果此时窗口贴近屏幕底部比较近，展开 10 条后会被遮挡，窗口没有自动调整，附件我提供视频。

https://github.com/auv1107/cleancliprun/assets/17818831/b47fdca8-340d-4be8-ae9b-d4cbd41c06e2

**Comment by s1ntoneli** [comment]
该版本中已修复，马上发布正式版：https://github.com/CleanClip/CleanClipApp/releases
